# Generated by Django 3.2.9 on 2021-11-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_band_like_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='to_delte',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
