# Generated by Django 3.2.9 on 2021-11-21 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_to_delte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='to_delte',
        ),
    ]
