# Generated by Django 3.2.9 on 2021-12-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litreview', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='identity',
            field=models.CharField(default='review', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='identity',
            field=models.CharField(default='ticket', max_length=100),
        ),
    ]
