# Generated by Django 3.2.9 on 2021-12-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litreview', '0006_auto_20211207_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answered',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
