# Generated by Django 3.2.9 on 2021-12-21 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='_authentication_user_follows_+', to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
